# Site settings
title: marion storm budwig
tagline: "practice & praxis repository"
url: "http://artistlivingandworking.lol"

# Contact
email: hello@artistlivingandworking.lol

imgur: artistlivingandworking

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
