# Site settings
title: Artist Living and Working
tagline: "stormy is an artist living and working"
url: "http://artistlivingandworking.lol"

# Contact
email: hello@artistlivindandworking.lol

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
